bazel_integration_test/BUILD, java/build/bazel/tests/integration/BUILD, tools/bazel.sh, tools/repositories.bzl
This way Bazel is unpacked only once per version for all the tests.
=> Unpack Bazel in the repository rule

WORKSPACE
https://github.com/bazelbuild/bazel-skylib/commit/2169ae1c374aab4a09aa90e65efe1a3aad4e279b
=> Update bazel-skylib to fix a small bug with versions.check()

javatests/build/bazel/tests/integration/BazelBaseTestCaseTest.java
https://ci.bazel.build/blue/organizations/jenkins/Global%2Fbazel-integration-testing/detail/bazel-integration-testing/156/pipeline/
=> Fix errorprone failure

tools/bazel.sh
@damienmg @ittaiz please review.
The local tests pass and also the tests that rely on this change also pass
=> support running tools/bazel script in java integration tests

.bazelci/presubmit.yml, .ci/bazel-integration-testing.json, README.md
apologies for missing your project when migrating to the new CI.
@ittaiz I have invited you to Buildkite. Please take a look at https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md for a getting started guide.
=> add config for new Bazel CI

README.md
currently it will show failing if any PR is failing.
Scoping it to master
=> added branch scoping to buildkite build badge

WORKSPACE, javatests/build/bazel/tests/integration/BUILD, javatests/build/bazel/tests/integration/BazelBaseTestCaseTest.java
* Added com.spotify:hamcrest-optional
=> scratchFile_Should_CreateFile_and_workspaceContents_ContainTheFile

java/build/bazel/tests/integration/WorkspaceDriver.java, javatests/build/bazel/tests/integration/WorkspaceDriverTest.java
Done from github UI, let’s see if build passes
=> Remove java.io.File

java/build/bazel/tests/integration/BazelCommand.java
currently it's methods are inaccessible (found it out while trying to use it)
=> make builder public

CODEOWNERS
I am no longer going to maintain projects in the bazelbuild org.
=> Remove damienmg@ from code owners

BUILD, WORKSPACE
=> Update rules_go to 0.16.3

tools/create_bazel_hashdict.py
__print()__ is a function in Python 3.
=> Use print() function in both Python 2 and Python 3

README.md, java/README.md
@jayconrod @achew22 @anchlovi would love your feedback
=> add more detailed readme

README.md
unfortunately according to @damienmg its no longer maintained :(
=> removed bazel eclipse from adopters

javatests/build/bazel/tests/integration/WorkspaceDriverTest.java
=> WorkspaceDriverTest to rely on runfiles from its own target

README.md
=> remove travis badge from readme

.bazelci/presubmit.yml, WORKSPACE, javatests/build/bazel/tests/integration/BUILD, javatests/build/bazel/tests/integration/RBEExampleTest.java
=> Add CI config to test on RBE

java/build/bazel/tests/integration/BazelCommand.java, javatests/build/bazel/tests/integration/BazelBaseTestCaseTest.java, tools/bazel_java_integration_test.bzl
=> tags now apply to the test suite as well as the specific test targets

README.md, java/README.md
We should provide users an easy setup example. By simply copy and paste, things should work.
I found some typos and possible improvements.
=> Improve jvm readme

WORKSPACE
=> update bazel-toolchains and http to https
